{
  "success"=>true,
  "elapsedMS"=>73,
  "warning"=>nil,
  "result"=>
    [
      {
        "generatorID"=>2,
        "imageID"=>166088,
        "displayName"=>"Y U No",
        "urlName"=>"Y-U-No",
        "totalVotesScore"=>9290,
        "instancesCount"=>2449676,
        "ranking"=>1,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>2, "totalVotesSum"=>11467,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
        "imageUrl"=>"https://memegenerator.net/img/images/400x/166088.jpg"
      },
      {
        "generatorID"=>542616,
        "imageID"=>2729805,
        "displayName"=>"Willy Wonka",
        "urlName"=>"Willy-Wonka",
        "totalVotesScore"=>2931,
        "instancesCount"=>2139091,
        "ranking"=>5,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>542616,
            "totalVotesSum"=>4088,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/2729805.jpg"
      },
      {
        "generatorID"=>74,
        "imageID"=>2485,
        "displayName"=>"The Most Interesting Man In The World",
        "urlName"=>"The-Most-Interesting-Man-In-The-World",
        "totalVotesScore"=>4957,
        "instancesCount"=>2070810,
        "ranking"=>3,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>74,
            "totalVotesSum"=>6822,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/2485.jpg"
      },
      {
        "generatorID"=>305,
        "imageID"=>84688,
        "displayName"=>"Futurama Fry",
        "urlName"=>"Futurama-Fry",
        "totalVotesScore"=>6388,
        "instancesCount"=>1828161,
        "ranking"=>2,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>305,
            "totalVotesSum"=>8241,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/84688.jpg"
      },
      {"generatorID"=>121,
        "imageID"=>1031,
        "displayName"=>"Success Kid",
        "urlName"=>"Success-Kid",
        "totalVotesScore"=>4559,
        "instancesCount"=>1546542,
        "ranking"=>6,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>121,
            "totalVotesSum"=>6174,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/1031.jpg"
      },
      {"generatorID"=>689854,
        "imageID"=>3291562,
        "displayName"=>"One Does Not Simply",
        "urlName"=>"One-Does-Not-Simply",
        "totalVotesScore"=>2594,
        "instancesCount"=>1400316,
        "ranking"=>7,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>689854,
            "totalVotesSum"=>3906,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/3291562.jpg"
      },
      {
        "generatorID"=>740857,
        "imageID"=>3459374,
        "displayName"=>"Bad Luck Brian",
        "urlName"=>"Bad-Luck-Brian",
        "totalVotesScore"=>2832,
        "instancesCount"=>1331490,
        "ranking"=>8,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>740857,
            "totalVotesSum"=>4092,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/3459374.jpg"
      },
      {
        "generatorID"=>340895,
        "imageID"=>2055789,
        "displayName"=>"First World Problems",
        "urlName"=>"First-World-Problems",
        "totalVotesScore"=>2068,
        "instancesCount"=>989659, "ranking"=>11,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>340895,
            "totalVotesSum"=>2865,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/2055789.jpg"
      },
      {
        "generatorID"=>17,
        "imageID"=>984,
        "displayName"=>"Philosoraptor",
        "urlName"=>"Philosoraptor",
        "totalVotesScore"=>9548,
        "instancesCount"=>835131,
        "ranking"=>4,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>17, "t
            otalVotesSum"=>12108,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/984.jpg"
      },
      {
        "generatorID"=>1771888,
        "imageID"=>6541210,
        "displayName"=>"Grumpy Cat ",
        "urlName"=>"Grumpy-Cat",
        "totalVotesScore"=>4042,
        "instancesCount"=>797470,
        "ranking"=>10,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>1771888,
            "totalVotesSum"=>2374,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/6541210.jpg"
      },
      {
        "generatorID"=>543246,
        "imageID"=>2732092,
        "displayName"=>"Winter is Coming",
        "urlName"=>"Winter-Is-Coming",
        "totalVotesScore"=>18,
        "instancesCount"=>624587,
        "ranking"=>23,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>543246,
            "totalVotesSum"=>401,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/2732092.jpg"
      },
      {
        "generatorID"=>116,
        "imageID"=>142442,
        "displayName"=>"Forever Alone",
        "urlName"=>"Forever-Alone",
        "totalVotesScore"=>3436,
        "instancesCount"=>551735,
        "ranking"=>12,
        "entityVotesSummary"=>
          {
            "entityName"=>"Generator",
            "entityID"=>116,
            "totalVotesSum"=>4231,
            "userID"=>-2060515646,
            "userVoteScore"=>0
          },
          "imageUrl"=>"https://memegenerator.net/img/images/400x/142442.jpg"
        }
      ]
}
